### login
POST http://localhost:8000/api/user/login
Content-Type: application/json

{
  "email": "timo.laakkonen@hotmail.com",
  "password": "Rytky#2025"
}


### register
POST http://localhost:8000/api/user/register
Content-Type: application/json

{  
  "email": "Simo.Saakkonen@hotmail.com",
  "password": "Rytky#2025",
  "username": "Simo Saakkonen"
}


### create document

POST http://localhost:8000/api/document
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYxZDc4MTgxOGFiODBhMDAxNDMwMzUiLCJ1c2VybmFtZSI6ImxhYWtrdGltYW4iLCJpYXQiOjE3Njg0NjYzODEsImV4cCI6MTc2ODQ2OTk4MX0.WKc6kqxHF6G0kDxJrbOvJxxoOq3850IXZXqlmAggqF8

{
  "title": "My first doc",
  "content": "Hello world"
}


### update document

PUT http://localhost:8000/api/document/6962e922993fc46701352efd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYyZTA0OGY3Mzc4NmI1M2IyYmI0MjYiLCJ1c2VybmFtZSI6IlNpbW8gU2Fha2tvbmVuIiwiaWF0IjoxNzY4MDg5NzI3LCJleHAiOjE3NjgwOTMzMjd9.ZKqoerouQ-_Ha27OW8xF8ZHXU4QjnJsIT3EREJFP0Y4

{
  "title": "Updated title",
  "content": "Updated content"
}


### delete document

DELETE http://localhost:8000/api/document/6962e89a993fc46701352efb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYyZTA0OGY3Mzc4NmI1M2IyYmI0MjYiLCJ1c2VybmFtZSI6IlNpbW8gU2Fha2tvbmVuIiwiaWF0IjoxNzY4MDg5NzI3LCJleHAiOjE3NjgwOTMzMjd9.ZKqoerouQ-_Ha27OW8xF8ZHXU4QjnJsIT3EREJFP0Y4


### get all documents by user

GET http://localhost:8000/api/document
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYyZTA0OGY3Mzc4NmI1M2IyYmI0MjYiLCJ1c2VybmFtZSI6IlNpbW8gU2Fha2tvbmVuIiwiaWF0IjoxNzY4MDk2OTM1LCJleHAiOjE3NjgxMDA1MzV9.vYC4qCOcIxuj9jHLPvI12tw7VY8JiIuoMikd7NPYSqw


### Add editor to document
POST http://localhost:8000/api/document/6964c75196e37f450b88c0fb/editors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYxZDc4MTgxOGFiODBhMDAxNDMwMzUiLCJ1c2VybmFtZSI6ImxhYWtrdGltYW4iLCJpYXQiOjE3NjgzMDA3NDIsImV4cCI6MTc2ODMwNDM0Mn0.oZdhtO4wm5C6VwDBbuV6gGpbXR9zsKslGWweHn3Taxg

{
  "userIdToAdd": "6962e048f73786b53b2bb426"
}

### Get all users
GET http://localhost:8000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYxZDc4MTgxOGFiODBhMDAxNDMwMzUiLCJ1c2VybmFtZSI6ImxhYWtrdGltYW4iLCJpYXQiOjE3NjgzMDgyMjAsImV4cCI6MTc2ODMxMTgyMH0.-WVqhQcL6i4hqBnR64UKdnv6SEvo9zlz2BV5wHjriiA